import matplotlib.pyplot as plt
import numpy as np
plt.rc('text',usetex=True)
plt.rc('font', family='sans-serif')
#plt.rc('font', sans-serif='Tahoma')
x=np.linspace(0,2*np.pi,100)
y=np.sin(x)
plt.ion()
plt.plot(x,y)
plt.xlabel(r'$\Delta t~{\rm in Gyr}$')
plt.xlim([0,np.pi])
plt.ylim([0,0.75])
plt.ylabel(r'$\Delta h$')
plt.title('Fun plotting example with oceans')
plt.savefig('example.pdf')